name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.2.3 # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  screenshot: ^2.1.0
  share_plus: ^7.2.2
  cupertino_icons: ^1.0.2
  flutter_font_picker: ^1.4.0
  google_fonts: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - google_fonts/
  uses-material-design: true



